# Generated by Django 5.2.1 on 2025-06-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='departure_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='destination',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='origin',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
